bug fixes example tests and more
projectdiscovery/tlsx pull request #163
Opened 2023-01-19 16:19 UTC by tarunKoyalwar

# Proposed Changes

- bug fix where openssl did not parse Cipher
- removed  deprecated `https://github.com/pkg/errors` in favour of `utils/errors`
- adds example to use tlsx as library 
- added input validation in clients

closes #128

2023-01-19 17:29 UTC, Mzack9999 requested changes
minor change in comment

2023-01-19 17:29 UTC, Mzack9999 commented on examples/simple.go
> +		// service.Connect(hostname ,ip ,port string)
not really an issue, but it would look much better correct spacing:
```go
service.Connect(hostname, ip , port string)
```

2023-01-20 10:26 UTC, Mzack9999 approved these changes

2023-01-20 14:16 UTC, ehsandeep approved these changes

2023-01-20 14:16 UTC, merged