cipher enum bug fixes and improvements
projectdiscovery/tlsx pull request #168
Opened 2023-01-24 10:58 UTC by tarunKoyalwar

# Proposed Changes

- TLS Version enumeration is enabled internally when using `-cipher-enum` flag
- Print Cipher Enum results in standard CLI mode (Only shown in JSON output now)
- Bug fix Missing OpenSSL ciphers in auto mode
-  Cipher Enum Optimization
   - Skip cipher enumeration in ctls mode when version is TLS 1.3 which caused false positives
   - Adds EnumMode and skip unsupported ciphers by client in Enum Mode

closes #167  #164

2023-01-24 11:07 UTC, tarunKoyalwar commented
![Screenshot 2023-01-24 at 4 36 16 PM](https://user-images.githubusercontent.com/45962551/214276109-b843eb3f-c5fe-4828-a0c6-fd3fd1496711.png)

2023-01-24 11:10 UTC, tarunKoyalwar commented
## Optimization

### Before 
```console
$ cmdutil ./tlsx -u scanme.sh -ve -ce -v 
  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\	v1.0.4

		projectdiscovery.io

[INF] Processing input scanme.sh:443
[openssl] does not support SSL_FORTEZZA_KEA_WITH_NULL_SHA cipher. skipping..
...
scanme.sh:443 [tls13,tls10,tls11,tls12]
[INF] Connections made using crypto/tls: 42, zcrypto/tls: 9, openssl: 1347

------------------------------
Command: ./tlsx -u scanme.sh -ve -ce -v
Max RSS: 37 MB
Sys Time: 904.162µs
User Time: 571.226µs
Actual Time: 11m54.194393083s
Voluntary Context Switch (nvcsw): 10902

```

### After
```console
$ cmdutil  ./tlsx -u scanme.sh -ce -v 
  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\	v1.0.4

		projectdiscovery.io

[INF] Processing input scanme.sh:443
scanme.sh:443 [tls13] [ECDHE-ECDSA-AES256-SHA,ECDHE-ECDSA-AES128-SHA]
scanme.sh:443 [tls12] [TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_RC4_128_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_FALLBACK_SCSV,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_ARIA_128_GCM_SHA256,ECDHE-ECDSA-CHACHA20-POLY1305,ECDHE-ECDSA-AES256-GCM-SHA384,ECDHE-ECDSA-AES256-SHA,ECDHE-ECDSA-AES128-GCM-SHA256,ECDHE-ECDSA-AES128-SHA]
scanme.sh:443 [tls10] [TLS_ECDHE_RSA_WITH_RC4_128_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,ECDHE-ECDSA-AES256-SHA,ECDHE-ECDSA-AES128-SHA]
scanme.sh:443 [tls11] [TLS_ECDHE_RSA_WITH_RC4_128_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,ECDHE-ECDSA-AES256-SHA,ECDHE-ECDSA-AES128-SHA]
[INF] Connections made using crypto/tls: 14, zcrypto/tls: 10, openssl: 11

------------------------------
Command: ./tlsx -u scanme.sh -ce -v
Max RSS: 36 MB
Sys Time: 910.905µs
User Time: 808.048µs
Actual Time: 3m53.450157083s
Voluntary Context Switch (nvcsw): 1417
```

2023-01-24 14:39 UTC, Mzack9999 requested changes

2023-01-24 14:39 UTC, Mzack9999 commented on go.mod
> +	github.com/projectdiscovery/stringsutil v0.0.2
I think you might need to change it to:
```
stringsutil github.com/projectdiscovery/utils/strings
```

2023-01-24 14:39 UTC, Mzack9999 commented on pkg/tlsx/openssl/openssl.go
> +	stringsutil "github.com/projectdiscovery/utils/strings"
same here

2023-01-25 07:41 UTC, Mzack9999 approved these changes

2023-01-25 10:13 UTC, ehsandeep approved these changes

2023-01-25 10:13 UTC, merged