Set read deadline while making tlsConn handshake
projectdiscovery/tlsx pull request #267
Opened 2023-05-25 14:35 UTC by RamanaReddy0M

2023-05-25 14:55 UTC, RamanaReddy0M commented
![Screenshot 2023-05-25 at 8 25 24 PM](https://github.com/projectdiscovery/tlsx/assets/90540245/6ea907c6-815a-463c-9e96-2f7f33114abc)

2023-05-25 19:31 UTC, ShubhamRasal commented
The issue mentioned above persists when using the `-ce` cipher enum with ztls.  With ctls taking approximately 1 minute to compute, ztls continues to experience hanging.
```console
tlsx on 🌱 issue-263-timeout-no [$?] via 🐹 v1.20.3 ⚛️ took 47s 
❯ time echo https://example.com  | ./tlsx -sm ctls  -retry 1 -ce
  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\	v1.0.9

		projectdiscovery.io

[INF] Current tlsx version v1.0.9 (latest)
[INF] Started TLS Cipher Enumeration using ctls mode
example.com:443 [tls10] [TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA]
example.com:443 [tls11] [TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA]
example.com:443 [tls12] [TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]

real	1m2.552s
user	0m0.989s
sys	0m0.400s


❯ time echo https://example.com  | ./tlsx -sm ztls  -retry 1 -ce
  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\	v1.0.9

		projectdiscovery.io

[INF] Current tlsx version v1.0.9 (latest)
[INF] Started TLS Cipher Enumeration using ztls mode
^C

real	2m7.189s
user	0m1.445s
sys	0m0.459s
```

2023-05-25 19:32 UTC, ShubhamRasal requested changes
The issue mentioned above persists when using the -ce cipher enum with ztls. With ctls taking approximately 1 minute to compute, ztls continues to experience hanging.
```console
tlsx on 🌱 issue-263-timeout-no [$?] via 🐹 v1.20.3 ⚛️ took 47s 
❯ time echo https://example.com  | ./tlsx -sm ctls  -retry 1 -ce
  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\	v1.0.9

		projectdiscovery.io

[INF] Current tlsx version v1.0.9 (latest)
[INF] Started TLS Cipher Enumeration using ctls mode
example.com:443 [tls10] [TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA]
example.com:443 [tls11] [TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA]
example.com:443 [tls12] [TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]

real	1m2.552s
user	0m0.989s
sys	0m0.400s


❯ time echo https://example.com  | ./tlsx -sm ztls  -retry 1 -ce
  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\	v1.0.9

		projectdiscovery.io

[INF] Current tlsx version v1.0.9 (latest)
[INF] Started TLS Cipher Enumeration using ztls mode
^C

real	2m7.189s
user	0m1.445s
sys	0m0.459s```

2023-05-26 07:49 UTC, ShubhamRasal commented
> The issue mentioned above persists when using the `-ce` cipher enum with ztls. With ctls taking approximately 1 minute to compute, ztls continues to experience hanging.
> 
> ```
> tlsx on 🌱 issue-263-timeout-no [$?] via 🐹 v1.20.3 ⚛️ took 47s 
> ❯ time echo https://example.com  | ./tlsx -sm ctls  -retry 1 -ce
>   
> 
>   _____ _    _____  __
>  |_   _| |  / __\ \/ /
>    | | | |__\__ \>  < 
>    |_| |____|___/_/\_\	v1.0.9
> 
> 		projectdiscovery.io
> 
> [INF] Current tlsx version v1.0.9 (latest)
> [INF] Started TLS Cipher Enumeration using ctls mode
> example.com:443 [tls10] [TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA]
> example.com:443 [tls11] [TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA]
> example.com:443 [tls12] [TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]
> 
> real	1m2.552s
> user	0m0.989s
> sys	0m0.400s
> 
> 
> ❯ time echo https://example.com  | ./tlsx -sm ztls  -retry 1 -ce
>   
> 
>   _____ _    _____  __
>  |_   _| |  / __\ \/ /
>    | | | |__\__ \>  < 
>    |_| |____|___/_/\_\	v1.0.9
> 
> 		projectdiscovery.io
> 
> [INF] Current tlsx version v1.0.9 (latest)
> [INF] Started TLS Cipher Enumeration using ztls mode
> ^C
> 
> real	2m7.189s
> user	0m1.445s
> sys	0m0.459s```
> ```

it is working with ztls, but as it has to range over many ciphers than ctls, it taking much longer time

2023-05-31 12:57 UTC, ShubhamRasal commented on pkg/tlsx/ztls/ztls.go
> +	// set read deadline
the select statement is not used correctly, as it should be used to wait for multiple channels simultaneously. In the current implementation, the tlsConn.Handshake() is called directly within the select statement, which blocks the select until the handshake is completed or an error occurs.

2023-05-31 14:38 UTC, ShubhamRasal approved these changes
lgtm 🚀

2023-06-01 00:18 UTC, ehsandeep approved these changes

2023-06-01 00:18 UTC, merged