fix false positive with untrusted flag
projectdiscovery/tlsx pull request #296
Opened 2023-06-29 11:05 UTC by RamanaReddy0M

2023-06-29 11:13 UTC, RamanaReddy0M commented
```console
✗ ./tlsx -un -host ebay.co.jp,comicon.it,sambonet.it
  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\  v1.1.0

                projectdiscovery.io

[INF] Current tlsx version v1.1.0 (latest)
sambonet.it:443
ebay.co.jp:443
comicon.it:443
[INF] Connections made using crypto/tls: 3, zcrypto/tls: 0, openssl: 0
```

2023-06-30 13:27 UTC, Mzack9999 requested changes
lgtm - I suggest moving the update certificate logic to a separate cmd utility (e.g., https://github.com/projectdiscovery/wappalyzergo/blob/main/cmd/update-fingerprints/main.go) that is run with a [cron-fashion](https://github.com/projectdiscovery/wappalyzergo/blob/main/.github/workflows/fingerprint-update.yml). Then it just gets loaded via embed, removing the need of reading/writing any external file as it gets included directly in the final binary:
```go
import (
	_ "embed"
)

//go:embed root_certs.pem
var data string
```

What do you think?

2023-07-04 09:15 UTC, Mzack9999 approved these changes
lgtm!
```console
$ go run . -un -host ebay.co.jp,comicon.it,sambonet.it
...
sambonet.it:443
comicon.it:443
ebay.co.jp:443
[INF] Connections made using crypto/tls: 3, zcrypto/tls: 0, openssl: 0
```

2023-07-04 12:01 UTC, ehsandeep approved these changes

2023-07-04 12:01 UTC, merged