sni flag enhancement
projectdiscovery/tlsx pull request #46
Opened 2022-07-07 21:24 UTC by LuitelSamikshya

2022-07-08 11:37 UTC, Mzack9999 approved these changes
Refactored the code to allow future options override via a custom `ConnectOptions` struct

2022-07-11 16:13 UTC, ehsandeep requested changes
- [ ] Adding SNI data in CLI output

Current:

```console
echo google.com | ./tlsx -vc -sni aa.txt -tps -silent

google.com:443 [failed] []
google.com:443 [failed] []
google.com:443 [failed] []
google.com:443 [failed] []
google.com:443 [success] [*.google.com]
google.com:443 [failed] []
```

Expected:

```console
echo google.com | ./tlsx -vc -sni aa.txt -tps -silent

google.com:443 [failed] [localhost]
google.com:443 [failed] [a]
google.com:443 [failed] [b]
google.com:443 [failed] [c]
google.com:443 [success] [*.google.com]
google.com:443 [failed] [d]
```

- [ ] Adding SNI field as part of default JSON output

```json
{
  "host": "google.com",
  "port": "443",
  "probe_status": true,
  "sni": "google.com",
}
```

2022-07-12 12:20 UTC, Mzack9999 approved these changes

2022-07-12 14:27 UTC, ehsandeep approved these changes

2022-07-12 14:29 UTC, merged