fix certificate mismatch validation logic
projectdiscovery/tlsx pull request #84
Opened 2022-09-13 08:49 UTC by parrasajad

fixes #76 , tests cases are passing now

2022-09-14 16:38 UTC, Ice3man543 approved these changes

2022-09-19 06:35 UTC, parrasajad commented on pkg/tlsx/clients/clients_test.go
> +		t.Run(tt.name, func(t *testing.T) {
i found this useful/faster when trying to find the failing test :)

2022-09-19 06:36 UTC, parrasajad commented on pkg/tlsx/clients/clients_test.go
> +				t.Errorf("matchWildCardToken() = %v, want %v", got, tt.want)
tried to follow the existing test present in the file.

2022-09-19 11:27 UTC, forgedhallpass commented on pkg/tlsx/clients/clients_test.go
> +		t.Run(tt.name, func(t *testing.T) {
Have you tried my suggestion? :) The first part literally does the same thing that you have right now, without hard-coding the name, and the second suggestion explicitly shows which test has failed, so you don't even need to look it up.

2022-09-19 11:28 UTC, forgedhallpass commented on pkg/tlsx/clients/clients_test.go
> +				t.Errorf("matchWildCardToken() = %v, want %v", got, tt.want)
That doesn't mean that it cannot be done better. It's exactly why there are assertion functions.

2022-09-19 11:29 UTC, forgedhallpass requested changes
See my comments

2022-09-19 14:11 UTC, merged